/**
 * Object storage port. The app stores event images (cover and logo) as objects and serves them
 * through its own route, so the bucket stays private and no storage credential or bucket URL ever
 * reaches a browser. Any S3-compatible service in the Saudi region works (docs/infrastructure.md).
 */
export interface StoredObject {
  body: Buffer;
  contentType: string;
}

export interface ObjectStorage {
  readonly kind: 's3' | 'local' | 'memory';
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
}

/** Object keys are generated by the app only: a folder and a random name, nothing user-typed. */
export const OBJECT_KEY_PATTERN = /^(event-media)\/[0-9A-Za-z]{22}\.(webp|png|jpg)$/;

export function assertObjectKey(key: string): void {
  if (!OBJECT_KEY_PATTERN.test(key)) throw new Error('invalid object key');
}

/** In-process storage for tests. */
export class MemoryStorage implements ObjectStorage {
  readonly kind = 'memory' as const;
  readonly objects = new Map<string, StoredObject>();

  async put(key: string, body: Buffer, contentType: string) {
    assertObjectKey(key);
    this.objects.set(key, { body: Buffer.from(body), contentType });
  }

  async get(key: string) {
    assertObjectKey(key);
    return this.objects.get(key) ?? null;
  }

  async delete(key: string) {
    assertObjectKey(key);
    this.objects.delete(key);
  }
}
